import { useState } from 'react'
import { supabase } from '../lib/supabase'
import { API_URL } from '../lib/config'
import { Calendar, Loader, Sparkles, Users, AlertTriangle, CheckCircle, List, Clock, Copy, Check } from 'lucide-react'

export default function MeetingBrief() {
  const [topic, setTopic] = useState('')
  const [brief, setBrief] = useState(null)
  const [loading, setLoading] = useState(false)
  const [copied, setCopied] = useState(false)

  async function generateBrief() {
    if (!topic.trim()) return
    setLoading(true)
    try {
      const { data: memories } = await supabase
        .from('memories')
        .select('title, content, created_at')

      const response = await fetch(`${API_URL}/api/meeting-brief`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ topic, memories })
      })

      const data = await response.json()
      if (data.error) throw new Error(data.error)
      setBrief(data)
    } catch (err) {
      console.error(err)
      alert('Error: ' + err.message)
    }
    setLoading(false)
  }

  function copyBrief() {
    if (!brief) return
    const text = `
MEETING BRIEF: ${brief.meeting_topic}
Generated by Second Brain AI

KEY CONTEXT:
${brief.key_context?.map(k => `• ${k}`).join('\n')}

OPEN ITEMS:
${brief.open_items?.map(o => `• ${o}`).join('\n')}

DECISIONS MADE:
${brief.decisions_made?.map(d => `• ${d}`).join('\n')}

SUGGESTED AGENDA:
${brief.suggested_agenda?.map((a, i) => `${i + 1}. ${a}`).join('\n')}

${brief.warning ? `⚠️ WARNING: ${brief.warning}` : ''}
    `.trim()
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="p-8 max-w-4xl mx-auto">

      {/* Header */}
      <div className="mb-8">
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <div className="bg-purple-600 text-white p-1.5 rounded-lg">
            <Calendar size={20} />
          </div>
          Smart Meeting Briefing
        </h1>
        <p className="text-gray-500 mt-1">
          Tell AI what your meeting is about — get instant context from all team memories
        </p>
      </div>

      {/* Input */}
      <div className="bg-white border border-gray-200 rounded-2xl p-6 mb-6">
        <label className="block text-sm font-medium text-gray-700 mb-2">
          What is your meeting about?
        </label>
        <div className="flex gap-3">
          <input
            value={topic}
            onChange={e => setTopic(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && generateBrief()}
            placeholder="e.g. Payment page redesign, Bug fixes, Sprint planning..."
            className="flex-1 border rounded-xl px-4 py-3 text-sm outline-none focus:border-purple-400"
          />
          <button
            onClick={generateBrief}
            disabled={loading || !topic.trim()}
            className="flex items-center gap-2 bg-purple-600 text-white px-5 py-3 rounded-xl text-sm font-medium hover:bg-purple-700 disabled:opacity-50 transition"
          >
            {loading ? <Loader size={16} className="animate-spin" /> : <Sparkles size={16} />}
            {loading ? 'Generating...' : 'Generate Brief'}
          </button>
        </div>

        {/* Quick suggestions */}
        <div className="flex gap-2 mt-3 flex-wrap">
          {['Payment page', 'Bug fixes', 'Sprint planning', 'Design review', 'Client update'].map(s => (
            <button
              key={s}
              onClick={() => setTopic(s)}
              className="text-xs bg-gray-100 hover:bg-purple-50 hover:text-purple-600 text-gray-600 px-3 py-1.5 rounded-full transition"
            >
              {s}
            </button>
          ))}
        </div>
      </div>

      {/* Loading */}
      {loading && (
        <div className="text-center py-16 bg-white border border-gray-200 rounded-2xl">
          <Loader className="animate-spin text-purple-600 mx-auto mb-4" size={32} />
          <p className="font-semibold text-gray-700">Scanning team memories...</p>
          <p className="text-gray-400 text-sm mt-2">Finding everything relevant to your meeting</p>
        </div>
      )}

      {/* Brief Results */}
      {brief && !loading && (
        <div className="space-y-4">

          {/* Brief Header */}
          <div className="bg-purple-600 text-white rounded-2xl p-6">
            <div className="flex items-start justify-between">
              <div>
                <p className="text-purple-200 text-sm mb-1">Meeting Brief for</p>
                <h2 className="text-xl font-bold">{brief.meeting_topic}</h2>
                {brief.last_discussed && (
                  <p className="text-purple-200 text-sm mt-2 flex items-center gap-1">
                    <Clock size={14} />
                    Last discussed: {brief.last_discussed}
                  </p>
                )}
              </div>
              <div className="flex flex-col items-end gap-2">
                <div className="bg-white bg-opacity-20 rounded-xl px-4 py-2 text-center">
                  <p className="text-2xl font-bold">{brief.relevance_score}%</p>
                  <p className="text-purple-200 text-xs">relevance</p>
                </div>
                <button
                  onClick={copyBrief}
                  className="flex items-center gap-1.5 bg-white bg-opacity-20 hover:bg-opacity-30 px-3 py-1.5 rounded-lg text-sm transition"
                >
                  {copied ? <Check size={14} /> : <Copy size={14} />}
                  {copied ? 'Copied!' : 'Copy Brief'}
                </button>
              </div>
            </div>
          </div>

          {/* Warning */}
          {brief.warning && (
            <div className="bg-red-50 border border-red-200 rounded-xl p-4 flex items-start gap-3">
              <AlertTriangle size={18} className="text-red-500 flex-shrink-0 mt-0.5" />
              <p className="text-sm text-red-700 font-medium">{brief.warning}</p>
            </div>
          )}

          {/* 4 column grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">

            {/* Key Context */}
            {brief.key_context?.length > 0 && (
              <div className="bg-white border border-gray-200 rounded-2xl p-5">
                <h3 className="font-semibold text-sm mb-3 flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-blue-500" />
                  Key Context
                </h3>
                <ul className="space-y-2">
                  {brief.key_context.map((item, i) => (
                    <li key={i} className="text-sm text-gray-600 flex items-start gap-2">
                      <span className="text-blue-400 mt-1 flex-shrink-0">•</span>
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Open Items */}
            {brief.open_items?.length > 0 && (
              <div className="bg-white border border-gray-200 rounded-2xl p-5">
                <h3 className="font-semibold text-sm mb-3 flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-red-500" />
                  Open Items to Address
                </h3>
                <ul className="space-y-2">
                  {brief.open_items.map((item, i) => (
                    <li key={i} className="text-sm text-gray-600 flex items-start gap-2">
                      <span className="text-red-400 mt-1 flex-shrink-0">•</span>
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Decisions Made */}
            {brief.decisions_made?.length > 0 && (
              <div className="bg-white border border-gray-200 rounded-2xl p-5">
                <h3 className="font-semibold text-sm mb-3 flex items-center gap-2">
                  <CheckCircle size={14} className="text-green-500" />
                  Previous Decisions
                </h3>
                <ul className="space-y-2">
                  {brief.decisions_made.map((item, i) => (
                    <li key={i} className="text-sm text-gray-600 flex items-start gap-2">
                      <span className="text-green-400 mt-1 flex-shrink-0">•</span>
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* People Involved */}
            {brief.people_involved?.length > 0 && (
              <div className="bg-white border border-gray-200 rounded-2xl p-5">
                <h3 className="font-semibold text-sm mb-3 flex items-center gap-2">
                  <Users size={14} className="text-purple-500" />
                  People Involved
                </h3>
                <div className="flex flex-wrap gap-2">
                  {brief.people_involved.map((person, i) => (
                    <span key={i} className="bg-purple-50 text-purple-700 text-sm px-3 py-1 rounded-full border border-purple-200">
                      {person}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Suggested Agenda */}
          {brief.suggested_agenda?.length > 0 && (
            <div className="bg-white border border-gray-200 rounded-2xl p-5">
              <h3 className="font-semibold text-sm mb-3 flex items-center gap-2">
                <List size={14} className="text-blue-500" />
                AI Suggested Agenda
              </h3>
              <ol className="space-y-2">
                {brief.suggested_agenda.map((item, i) => (
                  <li key={i} className="flex items-start gap-3 text-sm text-gray-600">
                    <span className="bg-blue-100 text-blue-700 rounded-full w-5 h-5 flex items-center justify-center text-xs font-medium flex-shrink-0 mt-0.5">
                      {i + 1}
                    </span>
                    {item}
                  </li>
                ))}
              </ol>
            </div>
          )}

        </div>
      )}
    </div>
  )
}