import { useState } from 'react'
import { supabase } from '../lib/supabase'
import { API_URL } from '../lib/config'
import { FileText, Loader, RefreshCw, CheckCircle, Clock, AlertTriangle, TrendingUp, Star, Copy, Check, Download } from 'lucide-react'

export default function WeeklyReport() {
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(false)
  const [copied, setCopied] = useState(false)

  async function generateReport() {
    setLoading(true)
    try {
      const { data: memories } = await supabase
        .from('memories')
        .select('title, content, created_at')

      if (!memories || memories.length === 0) {
        alert('No memories found!')
        setLoading(false)
        return
      }

      const response = await fetch(`${API_URL}/api/weekly-report`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ memories })
      })

      const data = await response.json()
      if (data.error) throw new Error(data.error)
      setReport(data)
    } catch (err) {
      console.error(err)
      alert('Error: ' + err.message)
    }
    setLoading(false)
  }

  function copyReport() {
    if (!report) return
    const text = `
WEEKLY TEAM REPORT — ${report.week}
Generated by Second Brain AI

${report.headline}

SUMMARY:
${report.summary}

✅ ACCOMPLISHED THIS WEEK:
${report.accomplished?.map(a => `• ${a}`).join('\n')}

🔄 IN PROGRESS:
${report.in_progress?.map(a => `• ${a}`).join('\n')}

🚫 BLOCKERS:
${report.blockers?.map(a => `• ${a}`).join('\n')}

📋 DECISIONS MADE:
${report.decisions?.map(a => `• ${a}`).join('\n')}

🎯 NEXT WEEK:
${report.next_week?.map(a => `• ${a}`).join('\n')}

🌟 TEAM HIGHLIGHTS:
${report.team_highlights?.map(a => `• ${a}`).join('\n')}

METRICS:
Tasks Completed: ${report.metrics?.tasks_completed}
Decisions Made: ${report.metrics?.decisions_made}
Bugs Fixed: ${report.metrics?.bugs_fixed}
Meetings Held: ${report.metrics?.meetings_held}
    `.trim()
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="p-8 max-w-4xl mx-auto">

      {/* Header */}
      <div className="mb-8 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <div className="bg-indigo-600 text-white p-1.5 rounded-lg">
              <FileText size={20} />
            </div>
            Weekly Report Generator
          </h1>
          <p className="text-gray-500 mt-1">
            AI generates a complete weekly team report from all your memories
          </p>
        </div>
        <button
          onClick={generateReport}
          disabled={loading}
          className="flex items-center gap-2 bg-indigo-600 text-white px-5 py-2.5 rounded-xl text-sm font-medium hover:bg-indigo-700 disabled:opacity-50 transition shadow-sm"
        >
          {loading ? <Loader size={16} className="animate-spin" /> : <RefreshCw size={16} />}
          {loading ? 'Generating...' : report ? 'Regenerate' : 'Generate Report'}
        </button>
      </div>

      {/* Empty state */}
      {!report && !loading && (
        <div className="text-center py-24 bg-white border border-gray-200 rounded-2xl">
          <div className="bg-indigo-50 w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <FileText className="text-indigo-600" size={32} />
          </div>
          <p className="font-semibold text-gray-700 text-lg">Generate Weekly Team Report</p>
          <p className="text-gray-400 text-sm mt-2 max-w-sm mx-auto">
            AI scans all memories and writes a professional weekly report you can send to stakeholders
          </p>
          <button
            onClick={generateReport}
            className="mt-6 bg-indigo-600 text-white px-6 py-3 rounded-xl text-sm font-medium hover:bg-indigo-700 transition"
          >
            Generate Now
          </button>
        </div>
      )}

      {/* Loading */}
      {loading && (
        <div className="text-center py-24 bg-white border border-gray-200 rounded-2xl">
          <Loader className="animate-spin text-indigo-600 mx-auto mb-4" size={32} />
          <p className="font-semibold text-gray-700">Writing your weekly report...</p>
          <p className="text-gray-400 text-sm mt-2">Summarizing accomplishments, decisions and next steps</p>
        </div>
      )}

      {/* Report */}
      {report && !loading && (
        <div className="space-y-4">

          {/* Report Header */}
          <div className="bg-indigo-600 text-white rounded-2xl p-6">
            <div className="flex items-start justify-between">
              <div>
                <p className="text-indigo-200 text-sm mb-1">Weekly Report — {report.week}</p>
                <h2 className="text-xl font-bold">{report.headline}</h2>
                <p className="text-indigo-200 text-sm mt-3 leading-relaxed">{report.summary}</p>
              </div>
              <button
                onClick={copyReport}
                className="flex items-center gap-1.5 bg-white bg-opacity-20 hover:bg-opacity-30 px-3 py-2 rounded-lg text-sm transition flex-shrink-0 ml-4"
              >
                {copied ? <Check size={14} /> : <Copy size={14} />}
                {copied ? 'Copied!' : 'Copy Report'}
              </button>
            </div>

            {/* Metrics */}
            {report.metrics && (
              <div className="grid grid-cols-4 gap-3 mt-4">
                {[
                  { label: 'Tasks Done', value: report.metrics.tasks_completed },
                  { label: 'Decisions', value: report.metrics.decisions_made },
                  { label: 'Bugs Fixed', value: report.metrics.bugs_fixed },
                  { label: 'Meetings', value: report.metrics.meetings_held },
                ].map(({ label, value }) => (
                  <div key={label} className="bg-white bg-opacity-15 rounded-xl p-3 text-center">
                    <p className="text-2xl font-bold">{value}</p>
                    <p className="text-indigo-200 text-xs mt-0.5">{label}</p>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Content Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">

            {/* Accomplished */}
            {report.accomplished?.length > 0 && (
              <div className="bg-white border border-gray-200 rounded-2xl p-5">
                <h3 className="font-semibold text-sm mb-3 flex items-center gap-2">
                  <CheckCircle size={16} className="text-green-500" />
                  Accomplished This Week
                </h3>
                <ul className="space-y-2">
                  {report.accomplished.map((item, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-gray-600">
                      <span className="text-green-400 mt-1">•</span>{item}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* In Progress */}
            {report.in_progress?.length > 0 && (
              <div className="bg-white border border-gray-200 rounded-2xl p-5">
                <h3 className="font-semibold text-sm mb-3 flex items-center gap-2">
                  <Clock size={16} className="text-blue-500" />
                  In Progress
                </h3>
                <ul className="space-y-2">
                  {report.in_progress.map((item, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-gray-600">
                      <span className="text-blue-400 mt-1">•</span>{item}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Blockers */}
            {report.blockers?.length > 0 && (
              <div className="bg-white border border-gray-200 rounded-2xl p-5">
                <h3 className="font-semibold text-sm mb-3 flex items-center gap-2">
                  <AlertTriangle size={16} className="text-red-500" />
                  Blockers
                </h3>
                <ul className="space-y-2">
                  {report.blockers.map((item, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-gray-600">
                      <span className="text-red-400 mt-1">•</span>{item}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Next Week */}
            {report.next_week?.length > 0 && (
              <div className="bg-white border border-gray-200 rounded-2xl p-5">
                <h3 className="font-semibold text-sm mb-3 flex items-center gap-2">
                  <TrendingUp size={16} className="text-purple-500" />
                  Next Week
                </h3>
                <ul className="space-y-2">
                  {report.next_week.map((item, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-gray-600">
                      <span className="text-purple-400 mt-1">•</span>{item}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>

          {/* Team Highlights */}
          {report.team_highlights?.length > 0 && (
            <div className="bg-yellow-50 border border-yellow-200 rounded-2xl p-5">
              <h3 className="font-semibold text-sm mb-3 flex items-center gap-2 text-yellow-800">
                <Star size={16} className="text-yellow-500" />
                Team Highlights
              </h3>
              <ul className="space-y-2">
                {report.team_highlights.map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-yellow-700">
                    <span className="mt-1">⭐</span>{item}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Decisions */}
          {report.decisions?.length > 0 && (
            <div className="bg-white border border-gray-200 rounded-2xl p-5">
              <h3 className="font-semibold text-sm mb-3 flex items-center gap-2">
                <CheckCircle size={16} className="text-indigo-500" />
                Decisions Made This Week
              </h3>
              <ul className="space-y-2">
                {report.decisions.map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-gray-600">
                    <span className="text-indigo-400 mt-1">•</span>{item}
                  </li>
                ))}
              </ul>
            </div>
          )}

        </div>
      )}
    </div>
  )
}